# Generated by Django 5.1.1 on 2024-09-25 07:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelD",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "medals",
                    models.CharField(
                        choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")], max_length=6
                    ),
                ),
                (
                    "medals_2",
                    models.CharField(
                        choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")], max_length=6
                    ),
                ),
                (
                    "yes_no",
                    models.CharField(blank=True, choices=[(None, "(Unknown)"), (0, "No"), (1, "Yes")], max_length=3),
                ),
                (
                    "yes_no_2",
                    models.CharField(blank=True, choices=[(None, "(Unknown)"), (0, "No"), (1, "Yes")], max_length=3),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modela",
            name="year_in_school_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "Freshman"),
                    ("SO", "Sophomore"),
                    ("JR", "Junior"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="modelb",
            name="media_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audio", [("vinyl", "Vinyl"), ("cd", "CD")]),
                    ("Video", [("vhs", "VHS Tape"), ("dvd", "DVD")]),
                    ("unknown", "Unknown"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="modelc",
            name="medals_2",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")], max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="modela",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="modelb",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="modelc",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="modelc",
            name="medals",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")], max_length=18
            ),
        ),
    ]
