# Generated by Django 3.1.7 on 2021-02-23 20:51

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelA",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "year_in_school",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelB",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "year_in_school",
                    models.CharField(
                        blank=True,
                        choices=[("FR", "Freshman"), ("SO", "Sophomore"), ("JR", "Junior"), ("SR", "Senior")],
                        max_length=2,
                    ),
                ),
                (
                    "media",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Audio", (("vinyl", "Vinyl"), ("cd", "CD"))),
                            ("Video", (("vhs", "VHS Tape"), ("dvd", "DVD"))),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelC",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "medals",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[("GOLD", "Gold"), ("SILVER", "Silver"), ("BRONZE", "Bronze")],
                        max_length=18,
                    ),
                ),
                (
                    "media",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Audio", (("vinyl", "Vinyl"), ("cd", "CD"))),
                            ("Video", (("vhs", "VHS Tape"), ("dvd", "DVD"))),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
